<a href="https://colab.research.google.com/github/usman-codez/Numpy_exercise/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
myarr = np.array([[3,5,6,8]])
myarr[0,2] = 56
print(myarr.shape)

(1, 4)


In [ ]:
listarr = np.array([[2,3,4],[5,6,3],[2,5,3]])
print(listarr)
print(listarr.dtype)
print(listarr.size)

[[2 3 4]
 [5 6 3]
 [2 5 3]]
int64
9


In [ ]:
emp = np.empty((2,3))
print(emp+2*3)

[[6. 6. 6.]
 [6. 6. 6.]]


In [ ]:
i = np.identity(3,dtype=np.int64)
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
x = np.array([[1,2,3],[3,2,4],[7,9,1]])
print(x)
print(x.sum(axis=1))

[[1 2 3]
 [3 2 4]
 [7 9 1]]
[ 6  9 17]


In [ ]:
print(x.T) #Transpose the matrix

[[1 3 7]
 [2 2 3]
 [3 4 1]]


In [ ]:
print(x.ndim)
print(x.nbytes)

2
72


In [ ]:
x.argsort()

array([[0, 1, 2],
       [1, 0, 2],
       [2, 0, 1]])

# ***Problem Sol***

In [ ]:
# Create a null vector of size 10
import numpy as np
null_vec = np.zeros(10)
print(null_vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#Find memory size of array
m = null_vec.nbytes
print(m)

80


In [ ]:
#Create a null vector of size 10 but the fifth value which is 1
n = np.zeros(10)
n[4]=1
print(n)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#Create a vector with values ranging from 10 to 49
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#Reverse a vector (first element becomes last)
print(v[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
#Create a 3x3 matrix with values ranging from 0 to 8
# mat = np.array([[0,1,2],[3,4,5],[6,7,8]])
mat = np.arange(0,9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
m = np.array([1,2,0,0,4,0])
print(m.nonzero())

(array([0, 1, 4]),)


In [ ]:
#Create a 3x3 identity matrix
i = np.identity(3,dtype=np.int64)
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
# Create a 3x3x3 array with random values
r = np.random.random((3,3,3))
print(r)

[[[0.48752848 0.20982825 0.15707859]
  [0.4630724  0.89785003 0.83500514]
  [0.78282275 0.36263054 0.60477971]]

 [[0.72595373 0.69003157 0.88679833]
  [0.69176606 0.20742211 0.37523   ]
  [0.37426727 0.63125621 0.42077213]]

 [[0.3944092  0.2695338  0.45436176]
  [0.35530413 0.46168629 0.91279121]
  [0.77145828 0.6071822  0.51724968]]]


In [ ]:
#Create a 10x10 array with random values and find the minimum and maximum values
a = np.random.random((10,10))
print(a.min())
print(a.max())

0.015499766401014914
0.994224214142627


In [ ]:
#Create a random vector of size 30 and find the mean value
rand = np.random.random(30)
print(rand.mean())

0.5837126173372958


In [ ]:
#Create a 2d array with 1 on the border and 0 inside
d = np.ones((5,5),dtype=int)
d[1:-1,1:-1]=0
print(d)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
#  How to add a border (filled with 0's) around an existing array?
import numpy as np
a = np.random.random((5,5))
a = np.pad(a,pad_width=1,mode='constant',constant_values=0)
print(a)

[[0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.4081297  0.55202053 0.05089339 0.00572605 0.71669534
  0.        ]
 [0.         0.91993644 0.18736278 0.10699371 0.63523734 0.28411768
  0.        ]
 [0.         0.49544389 0.93473269 0.99833192 0.51816281 0.300609
  0.        ]
 [0.         0.10648577 0.15989946 0.85993505 0.76868369 0.24949292
  0.        ]
 [0.         0.0096188  0.17954645 0.25134992 0.05218603 0.09424936
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.        ]]


In [ ]:
#What the result of the following
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [ ]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
a = np.diag(np.arange(1,5),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
#Create a 8x8 matrix and fill it with a checkerboard pattern
c = np.zeros((8,8))
c[1::2,::2]=1
c[::2,1::2]=1
print(c)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [ ]:
#Create a checkerboard 8x8 matrix using the tile function
a = np.tile(np.array([[1,0],[0,1]]),(4,4))
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [ ]:
#Normalize a 5x5 random matrix
#Method_1
# a = np.random.random((5,5))
# nor = a-np.mean(a)
# print(nor)

#Method_2
a = np.random.random((5,5))
m = a.max()
mi = a.min()
nor = (a-mi)/(m-mi)
print(nor)

[[0.52281606 0.23899417 0.98313993 0.01803158 0.31257582]
 [0.80301471 0.16919945 0.60526013 0.74744182 0.44700906]
 [0.08063681 0.60036057 1.         0.16786898 0.4542833 ]
 [0.99999693 0.55023294 0.79458534 0.60580198 0.81139468]
 [0.90289337 0.99986652 0.         0.05597782 0.76454313]]


In [ ]:
#Create a custom dtype that describes a color as four unsigned bytes (RGBA)
cus = np.dtype([
    ('r',np.ubyte,1),
    ('g',np.ubyte,1),
    ('b',np.ubyte,1),
    ('a',np.ubyte,1)
])
print(cus)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-34-88ff5ecbab54>:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  cus = np.dtype([


In [ ]:
#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
a = np.array([[2,3,4],[3,4,5],[12,4,9],[2,7,4],[1,1,1]])
b = np.array([[2,3],[4,1],[1,3]])
# prod1 = np.dot(a,b)
prod2 = a @ b
# print(prod1)
print(prod2)

[[20 21]
 [27 28]
 [49 67]
 [36 25]
 [ 7  7]]


In [ ]:
# Given a 1D array, negate all elements which are between 3 and 8, in place.
arr = np.array([2,3,6,1,7,4,6,1,2])
arr[(arr>3) & (arr<8)] *= -1
print(arr)

[ 2  3 -6  1 -7 -4 -6  1  2]


In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
import numpy as np
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-2-779629cb3f15>:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-2-779629cb3f15>:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-2-779629cb3f15>:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [ ]:
# How to round away from zero a float array ?
z = np.random.uniform(-10,+10,10)
print(z)
a = np.abs(z)
c = np.ceil(a)
s = np.copysign(c,z)
print(s)

[ 7.78281047 -5.31317088  9.57428741 -1.58557591 -7.69770122 -5.36227695
  5.33288639  5.71194673 -4.34804207  7.95661598]
[ 8. -6. 10. -2. -8. -6.  6.  6. -5.  8.]


In [ ]:
# How to find common values between two arrays?
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
common = np.intersect1d(a,b)
print(a)
print(b)
print(common)

[9 5 6 9 6 5 6 9 1 7]
[6 0 6 1 4 9 9 9 8 6]
[1 6 9]


In [ ]:
import numpy as np
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
print(Z)

# Back to sanity
_ = np.seterr(**defaults)

# An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0
    print(Z)

[inf]
{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}
[inf]


In [ ]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
np.sqrt(-1) == np.emath.sqrt(-1)

nan
1j


<ipython-input-8-1a00e04f85bb>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))
<ipython-input-8-1a00e04f85bb>:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [ ]:
# How to get the dates of yesterday, today and tomorrow?
yes = np.datetime64('Today','D') - np.timedelta64(1,'D')
tod = np.datetime64('Today','D')
tom = np.datetime64('Today','D') + np.timedelta64(1,'D')
print(yes)
print(tod)
print(tom)

2024-09-22
2024-09-23
2024-09-24


In [ ]:
#  How to get all the dates corresponding to the month of July 2016?
d = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(d)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
# How to compute ((A+B)*(-A/2)) in place (without copy)?
A = np.array([[1,2],[8,4]])
B = np.array([[4,6],[2,1]])
np.add(A,B,out=B)
np.divide(A,2,out=A, casting='unsafe')
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([[  0,  -8],
       [-40, -10]])

In [ ]:
# Extract the integer part of a random array using 5 different methods
a = np.random.uniform(0,10,10)
print(a)
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.fix(a))
print(a.astype(int))
print(np.round(a))

[8.17191529 3.10690054 0.45336904 3.76212958 4.88613332 6.71761498
 0.16729837 3.75315622 3.57885934 8.70392984]
[8. 3. 0. 3. 4. 6. 0. 3. 3. 8.]
[9. 4. 1. 4. 5. 7. 1. 4. 4. 9.]
[8. 3. 0. 3. 4. 6. 0. 3. 3. 8.]
[8. 3. 0. 3. 4. 6. 0. 3. 3. 8.]
[8 3 0 3 4 6 0 3 3 8]
[8. 3. 0. 4. 5. 7. 0. 4. 4. 9.]


In [ ]:
# Create a 5x5 matrix with row values ranging from 0 to 4
m = np.zeros((5,5))
m += np.arange(5)
print(m)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
# Consider a generator function that generates 10 integers and use it to build an array
import numpy as np
def gen():
  for i in range(10):
    yield i

a = gen()
arr = np.array(list(a))
print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded
a = np.linspace(0,1,11,endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
# Create a random vector of size 10 and sort it
a = np.random.random(10)
print(np.sort(a))

[0.0064951  0.10376412 0.16219448 0.30229713 0.3669538  0.56264353
 0.58652571 0.78471315 0.88290744 0.98930255]


In [ ]:
# How to sum a small array faster than np.sum?
z = np.arange(10)
print(sum(z))

45


In [ ]:
#  Consider two random array A and B, check if they are equal
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

eq = np.allclose(A,B)
print(eq)

e = np.array_equal(A,B)
print(e)

False
False


In [ ]:
# Make an array immutable (read-only)
a = np.random.randint(0,15,10)
# a.setflags(write=False)
a.flags.writeable=False
print(a)

[ 9  0  0  9 11  5  1  1 14 14]


In [ ]:
# Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
a = np.random.random((2,10))
x,y = a[:,0],a[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.31735176 0.42690387]
[0.36019638 0.58184687]
[0.4927146  0.74703772]


In [ ]:
import pandas as pd
a = {
    'name': ['ali','usman'],
    'no': [846,932],
    'mail': 'usmanx,usga'
}
d= pd.DataFrame(a)
print(d)


    name   no         mail
0    ali  846  usmanx,usga
1  usman  932  usmanx,usga
